FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app
COPY EkosWizard.sln .
COPY src/ src/
RUN dotnet restore
RUN dotnet publish src/EkosWizard.Api/EkosWizard.Api.csproj -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /out .
EXPOSE 8080
ENTRYPOINT ["dotnet", "ImpWizard.Api.dll"]
